# Generated by Django 4.1.6 on 2023-05-12 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart1", "0002_order_total"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
