# Generated by Django 4.1.6 on 2023-05-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart1", "0003_orderitem_total_price_alter_orderitem_quantity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total",
            new_name="total_price",
        ),
        migrations.RenameField(
            model_name="orderitem",
            old_name="total_price",
            new_name="price",
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
