# Generated by Django 4.1.6 on 2023-05-12 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart1", "0005_alter_orderitem_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="quantity",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
    ]
