# Generated by Django 4.1.6 on 2023-05-12 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart1", "0010_rename_total_price_orderitem_total_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
