# Generated by Django 4.1.6 on 2023-05-12 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart1", "0013_orderitem_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="total_price",
        ),
    ]
