# Generated by Django 4.1.6 on 2023-05-08 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_mymodel_customer_password_product_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MyModel",
            new_name="Product_Image",
        ),
    ]
