# Generated by Django 4.1.6 on 2023-05-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0006_remove_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=128),
        ),
    ]
