# Generated by Django 4.1.6 on 2023-05-08 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0008_alter_customer_password"),
    ]

    operations = []
