# Generated by Django 4.1.6 on 2023-05-08 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0009_auto_20230508_1057"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product_Image",
        ),
    ]
