# Generated by Django 4.1.6 on 2023-05-08 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0012_alter_customer_password"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="password",
            new_name="password_hash",
        ),
    ]
