# Generated by Django 4.1.6 on 2023-05-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0013_rename_password_customer_password_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="password_hash",
        ),
        migrations.AddField(
            model_name="customer",
            name="password",
            field=models.CharField(default="default_password", max_length=128),
        ),
    ]
