# Generated by Django 4.1.6 on 2023-05-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0014_remove_customer_password_hash_customer_password"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product_Image",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
